/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;


import Comands.*;
import FrameManager.ImageFrameManagerUtil;


import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import static java.lang.Thread.sleep;

import java.net.URL;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author diego
 */
public class FrameClient extends JFrame {

    private Client client;
    private JPanel pnlImgFondo;
    private static final int CORRECT_EXIT = 0;
    /**
     * Creates new form FrameClient
     */
    public FrameClient() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initImages();
        String name = JOptionPane.showInputDialog(this, "Ingrese su nombre");
        this.setTitle(name);
        client =  new Client(this, name);
        
    }
    
    /*El método muestra una ventana con un error de nombre y solicita
          nuevamente el nombre al usuario, haciendo el request al servidor.
        */
    public void showNameError(){
        if (this.client == null){
            return;
        }
        String name = JOptionPane.showInputDialog(this, "Ingrese su nombre", "Error en el nombre", JOptionPane.ERROR_MESSAGE);
        this.setTitle(name);
        client.name = name;
        client.sendName();
        
    }
    
    
    /*Cambia el fondo de la pantalla y también el icono de la ventana*/
    private void initImages(){
        ((JPanel)getContentPane()).setOpaque(false);
        Image imgFrameClient = new ImageIcon(getClass()
                .getResource("/ImagenesFondos/ImagenFondoFrameClient.png")).getImage()
                .getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        this.setIconImage(imgFrameClient);
        pnlImgFondo = ImageFrameManagerUtil.createPanelWithImage("/ImagenesFondos/ImagenFondoFrameClient.png");
        pnlImgFondo.setBounds(0, 0, getWidth(), getHeight()); //Se ajusta al tamaño del frame
        pnlImgFondo.setOpaque(false); // Así no tapa el uso de otros componentes

        // Así se agrega el panel al layered pane en la capa más baja
        getLayeredPane().add(pnlImgFondo, Integer.valueOf(Integer.MIN_VALUE));
        
        //Así el tamaño de la imagen de fondo es reajustable siempre que el usuario lo desee
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                if (pnlImgFondo != null) {
                    pnlImgFondo.setBounds(0, 0, getWidth(), getHeight());
                    pnlImgFondo.repaint();
                }
            }
        });
    }

    /*El metodo revalida y repinta la ventana en su totalidad*/
    public void refreshFrame(){
        this.revalidate();
        this.repaint();
    }
    
    private void cleanCommandWritter(){
        this.txfCommand.setText("");
        this.repaint();
    }

    public void writeMessage(String msg){
        txaMessages.append(msg + "\n");
        this.refreshFrame();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaMessages = new javax.swing.JTextArea();
        txfCommand = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaEnemyStats = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaRanking = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();
        pnlOceanMap = new javax.swing.JPanel();
        pnlAttackReceived = new javax.swing.JPanel();
        pnlOceanMapGrid2 = new javax.swing.JPanel();
        pnlWarriors = new javax.swing.JPanel();
        lblWarriorImage1 = new javax.swing.JLabel();
        lblWarriorImage2 = new javax.swing.JLabel();
        lblWarriorImage3 = new javax.swing.JLabel();
        lblWarriorImage4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaWarriorData = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txaMyStats = new javax.swing.JTextArea();
        pnlColumnsHeader = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        txaMessages.setColumns(20);
        txaMessages.setRows(5);
        jScrollPane1.setViewportView(txaMessages);

        txfCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCommandActionPerformed(evt);
            }
        });
        txfCommand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfCommandKeyReleased(evt);
            }
        });

        btnSend.setText("SEND");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        txaEnemyStats.setColumns(20);
        txaEnemyStats.setRows(5);
        jScrollPane2.setViewportView(txaEnemyStats);

        txaRanking.setColumns(20);
        txaRanking.setRows(5);
        jScrollPane3.setViewportView(txaRanking);

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        pnlOceanMap.setBackground(new java.awt.Color(102, 255, 102));
        pnlOceanMap.setOpaque(false);
        pnlOceanMap.setPreferredSize(new java.awt.Dimension(600, 600));

        pnlAttackReceived.setBackground(new java.awt.Color(102, 102, 102));
        pnlAttackReceived.setPreferredSize(new java.awt.Dimension(515, 400));

        javax.swing.GroupLayout pnlAttackReceivedLayout = new javax.swing.GroupLayout(pnlAttackReceived);
        pnlAttackReceived.setLayout(pnlAttackReceivedLayout);
        pnlAttackReceivedLayout.setHorizontalGroup(
            pnlAttackReceivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        pnlAttackReceivedLayout.setVerticalGroup(
            pnlAttackReceivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        pnlOceanMapGrid2.setBackground(new java.awt.Color(102, 102, 102));
        pnlOceanMapGrid2.setPreferredSize(new java.awt.Dimension(515, 400));

        javax.swing.GroupLayout pnlOceanMapGrid2Layout = new javax.swing.GroupLayout(pnlOceanMapGrid2);
        pnlOceanMapGrid2.setLayout(pnlOceanMapGrid2Layout);
        pnlOceanMapGrid2Layout.setHorizontalGroup(
            pnlOceanMapGrid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        pnlOceanMapGrid2Layout.setVerticalGroup(
            pnlOceanMapGrid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlOceanMapLayout = new javax.swing.GroupLayout(pnlOceanMap);
        pnlOceanMap.setLayout(pnlOceanMapLayout);
        pnlOceanMapLayout.setHorizontalGroup(
            pnlOceanMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOceanMapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOceanMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAttackReceived, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(pnlOceanMapGrid2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOceanMapLayout.setVerticalGroup(
            pnlOceanMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOceanMapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAttackReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlOceanMapGrid2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlWarriors.setBackground(new java.awt.Color(51, 255, 51));
        pnlWarriors.setOpaque(false);

        lblWarriorImage2.setBackground(new java.awt.Color(255, 255, 255));

        txaWarriorData.setColumns(20);
        txaWarriorData.setRows(5);
        jScrollPane4.setViewportView(txaWarriorData);

        javax.swing.GroupLayout pnlWarriorsLayout = new javax.swing.GroupLayout(pnlWarriors);
        pnlWarriors.setLayout(pnlWarriorsLayout);
        pnlWarriorsLayout.setHorizontalGroup(
            pnlWarriorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWarriorsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWarriorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlWarriorsLayout.createSequentialGroup()
                        .addComponent(lblWarriorImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWarriorImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWarriorImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWarriorImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        pnlWarriorsLayout.setVerticalGroup(
            pnlWarriorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWarriorsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlWarriorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWarriorImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarriorImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarriorImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarriorImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        txaMyStats.setColumns(20);
        txaMyStats.setRows(5);
        jScrollPane9.setViewportView(txaMyStats);

        pnlColumnsHeader.setPreferredSize(new java.awt.Dimension(515, 52));
        pnlColumnsHeader.setLayout(new java.awt.GridLayout(1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(pnlOceanMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlWarriors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlColumnsHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 1203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pnlColumnsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlWarriors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlOceanMap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE))
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        //obnter string del txf y quitar espacio
        String msg =  txfCommand.getText().trim();
        if (msg.length()>0){
            String args[] = CommandUtil.tokenizerArgs(msg);
            if (args.length > 0){
                Command comando = CommandFactory.getCommand(args);
                if (comando != null){
                    try {
                        client.objectSender.writeObject(comando);
                    } catch (IOException ex) {
                        
                    }
                }else{
                    this.writeMessage("Error: comando desconocido");
                }
                
            }
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnCloseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(FrameClient.CORRECT_EXIT);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txfCommandActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txfCommandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCommandActionPerformed

    private void txfCommandKeyReleased(KeyEvent evt) {//GEN-FIRST:event_txfCommandKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            //obnter string del txf y quitar espacio
            String msg =  txfCommand.getText().trim();
            if (msg.length()>0){
                String args[] = CommandUtil.tokenizerArgs(msg);
                if (args.length > 0){
                    Command comando = CommandFactory.getCommand(args);
//                    if (!client.isDead() && !DisponibilityCheckerOfCommand.checkInicialCommandDisponibilty(comando, this.client.isIsReady(), client.getFighterRegister().getFighters())){
//                        this.writeMessage("Error: comando no permitido");
//                        this.cleanCommandWritter();
//                        return;
//                    }
                    if (client.isDead() && !DisponibilityCheckerOfCommand.checkDeadCommandDisponibility(comando)){
                        this.writeMessage("Error: comando no permitido");
                        this.cleanCommandWritter();
                        return;
                    }
                    if (comando != null){
                        try {
                            client.objectSender.writeObject(comando);
                            client.objectSender.flush();
                        } catch (IOException ex) {

                        }
                    }else{
                        this.writeMessage("Error: comando desconocido");
                    }

                }
            }
            this.cleanCommandWritter();
        }
    }//GEN-LAST:event_txfCommandKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrameClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(FrameClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FrameClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrameClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblWarriorImage1;
    private javax.swing.JLabel lblWarriorImage2;
    private javax.swing.JLabel lblWarriorImage3;
    private javax.swing.JLabel lblWarriorImage4;
    private javax.swing.JPanel pnlAttackReceived;
    private javax.swing.JPanel pnlColumnsHeader;
    private javax.swing.JPanel pnlOceanMap;
    private javax.swing.JPanel pnlOceanMapGrid2;
    private javax.swing.JPanel pnlWarriors;
    private javax.swing.JTextArea txaEnemyStats;
    private javax.swing.JTextArea txaMessages;
    private javax.swing.JTextArea txaMyStats;
    private javax.swing.JTextArea txaRanking;
    private javax.swing.JTextArea txaWarriorData;
    private javax.swing.JTextField txfCommand;
    // End of variables declaration//GEN-END:variables
}
